[build]
  base = ""
  command = "cd client && npm install && npm run build"
  publish = "client/build"

[build.environment]
  NODE_VERSION = "16.14.0"
  NPM_VERSION = "8.5.0"

# Handle SPA routing (for React Router)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 